// Static i18n for the Products / Suppliers (catalog) feature. Passed to useString({ str }).
const catalogStrings: Record<string, Record<string, string>> = {
    products: { ukr: "товари", eng: "products" },
    product: { ukr: "товар", eng: "product" },
    suppliers: { ukr: "постачальники", eng: "suppliers" },
    supplier: { ukr: "постачальник", eng: "supplier" },
    productStatuses: { ukr: "статуси товару", eng: "product statuses" },
    productStatus: { ukr: "статус товару", eng: "product status" },
    supplierStatuses: { ukr: "статуси постачальника", eng: "supplier statuses" },
    supplierStatus: { ukr: "статус постачальника", eng: "supplier status" },
    supplierProductStatuses: { ukr: "статуси товару у постачальника", eng: "supplier product statuses" },
    supplierProductStatus: { ukr: "статус товару у постачальника", eng: "supplier product status" },
    importCodes: { ukr: "коди УКТЗЕД", eng: "import codes" },
    importCode: { ukr: "код УКТЗЕД", eng: "import code" },
    productTypes: { ukr: "типи товару", eng: "product types" },
    productType: { ukr: "тип товару", eng: "product type" },
    taxTypes: { ukr: "податкові типи", eng: "tax types" },
    taxType: { ukr: "податковий тип", eng: "tax type" },
    taxRates: { ukr: "ставки податків", eng: "tax rates" },
    taxRate: { ukr: "ставка податку", eng: "tax rate" },
    productTaxes: { ukr: "податки товарів", eng: "product taxes" },
    productTax: { ukr: "податок товару", eng: "product tax" },
    rate: { ukr: "ставка", eng: "rate" },
    effectiveFrom: { ukr: "діє з", eng: "effective from" },
    effectiveTill: { ukr: "діє до", eng: "effective till" },
    ean: { ukr: "штрихкод", eng: "EAN" },
    eans: { ukr: "штрихкоди", eng: "EANs" },
    noEans: { ukr: "штрихкодів немає", eng: "No EANs" },
    searchByEan: { ukr: "пошук за штрихкодом", eng: "search by EAN" },
    productCard: { ukr: "картка товару", eng: "product card" },
    copy: { ukr: "копіювати", eng: "copy" },
    copied: { ukr: "скопійовано", eng: "copied" },
    clear: { ukr: "очистити", eng: "clear" },
    associations: { ukr: "зв'язки товар–постачальник", eng: "product–supplier links" },
    market: { ukr: "ринок", eng: "market" },
    segment: { ukr: "сегмент", eng: "segment" },
    category: { ukr: "категорія", eng: "category" },
    family: { ukr: "родина", eng: "family" },
    nomenclature: { ukr: "номенклатура", eng: "nomenclature" },
    status: { ukr: "статус", eng: "status" },
    code: { ukr: "код", eng: "code" },
    name: { ukr: "назва", eng: "name" },
    description: { ukr: "опис", eng: "description" },
    search: { ukr: "пошук", eng: "search" },
    filters: { ukr: "фільтри", eng: "filters" },
    resetFilters: { ukr: "скинути фільтри", eng: "reset filters" },
    any: { ukr: "будь-який", eng: "any" },
    productCode: { ukr: "код товару", eng: "product code" },
    productName: { ukr: "назва товару", eng: "product name" },
    supplierCode: { ukr: "код постачальника", eng: "supplier code" },
    supplierName: { ukr: "назва постачальника", eng: "supplier name" },
    add: { ukr: "додати", eng: "add" },
    edit: { ukr: "редагувати", eng: "edit" },
    delete: { ukr: "видалити", eng: "delete" },
    create: { ukr: "створити", eng: "create" },
    save: { ukr: "зберегти", eng: "save" },
    cancel: { ukr: "скасувати", eng: "cancel" },
    confirmDelete: { ukr: "підтвердити видалення", eng: "confirm delete" },
    deletePrompt: { ukr: "видалити цей запис?", eng: "Delete this record?" },
    required: { ukr: "обов'язкове поле", eng: "required" },
    max_length: { ukr: "перевищено максимальну довжину", eng: "max length exceeded" },
    selectPlaceholder: { ukr: "оберіть…", eng: "select…" },
    admin: { ukr: "адміністрування", eng: "admin" },
    noNomenclature: { ukr: "без номенклатури", eng: "no nomenclature" },
};
export default catalogStrings;
