// Static i18n for the Nomenclature feature. Passed to useString({ str }).
// DB-managed strings (translationsStore) still take precedence.
const nomenclatureStrings: Record<string, Record<string, string>> = {
    nomenclature: { ukr: "номенклатура", eng: "nomenclature" },
    markets: { ukr: "ринки", eng: "markets" },
    market: { ukr: "ринок", eng: "market" },
    segments: { ukr: "сегменти", eng: "segments" },
    segment: { ukr: "сегмент", eng: "segment" },
    categories: { ukr: "категорії", eng: "categories" },
    category: { ukr: "категорія", eng: "category" },
    families: { ukr: "родини", eng: "family" },
    family: { ukr: "родина", eng: "family" },
    keys: { ukr: "ключі", eng: "keys" },
    key_name: { ukr: "назва ключа", eng: "key name" },
    links: { ukr: "зв'язки", eng: "links" },
    keyLinks: { ukr: "ключі (дерево)", eng: "key links" },
    key_link_level: { ukr: "рівень ключа", eng: "key link level" },
    key_tree: { ukr: "дерево ключів", eng: "key tree" },
    key_level_1: { ukr: "ключі рівня 1", eng: "level 1 keys" },
    key_level_2: { ukr: "ключі рівня 2", eng: "level 2 keys" },
    key_level_3: { ukr: "ключі рівня 3", eng: "level 3 keys" },
    select_family_to_view_keys: { ukr: "оберіть родину щоб побачити дерево ключів", eng: "Select a family to view its key tree" },
    no_level1_keys: { ukr: "немає ключів рівня 1", eng: "No level 1 keys" },
    no_children: { ukr: "немає дочірніх", eng: "no children" },
    status: { ukr: "статус", eng: "status" },
    code: { ukr: "код", eng: "code" },
    name: { ukr: "назва", eng: "name" },
    createdAt: { ukr: "створено", eng: "created" },
    admin: { ukr: "адміністрування", eng: "admin" },
    add: { ukr: "додати", eng: "add" },
    edit: { ukr: "редагувати", eng: "edit" },
    delete: { ukr: "видалити", eng: "delete" },
    create: { ukr: "створити", eng: "create" },
    save: { ukr: "зберегти", eng: "save" },
    cancel: { ukr: "скасувати", eng: "cancel" },
    confirmDelete: { ukr: "підтвердити видалення", eng: "confirm delete" },
    deletePrompt: { ukr: "видалити цей запис?", eng: "Delete this record?" },
    required: { ukr: "обов'язкове поле", eng: "required" },
    max_length: { ukr: "перевищено максимальну довжину", eng: "max length exceeded" },
    selectPlaceholder: { ukr: "оберіть…", eng: "select…" },
};
export default nomenclatureStrings;
